### ISSUE TITLE
Extract code related to sqllogictest to separate library

### ISSUE THREAD

**Issue by dssysolyatin** [vmware/sql-to-dbsp-compiler#138]
Hi!
First, your project is awesome! I read an article and it looks very promising!

One of the project in our company can be expose to an user as postgres server (it supports postgres wire protocol and postgres syntax) and I was trying to test it using original sqllogictest util. But I faced with issue that if I run sqllogictest util using -odbc option it generates different hashes for `test/select*.test` even if use raw postgres. I asked help at sqllite forum about this problem - https://sqlite.org/forum/forumpost/36b1c1fd70, but unfortunately, I have not yet received any responses

I tried your JDBCExecutor and it works as expected! It would be nice if it could be extracted to separate library.

**Comment by mbudiu-vmw** [comment]
Now we have factored this out into a separate general-purpose tool: https://github.com/hydromatic/sql-logic-test
