### ISSUE TITLE
Cannot run this on Mac (M1)

### ISSUE THREAD

**Issue by GiridharaSPK** [vmware/sql-to-dbsp-compiler#61]
tried to run the run-tests.sh in my mac, it is throwing the following error
<img width="1440" alt="Screen Shot 2022-11-17 at 1 21 37 PM" src="https://user-images.githubusercontent.com/27071146/202527133-e3807eee-6814-45e8-8ef9-44dd833cfc88.png">

<img width="1440" alt="Screen Shot 2022-11-17 at 1 21 54 PM" src="https://user-images.githubusercontent.com/27071146/202527158-f15634d3-02a8-42eb-b697-68eed413870b.png">

**Comment by mbudiu-vmw** [comment]
Can you run the DBSP tests by themselves?
If not, you cannot expect to run the SQL compiler tests either.

**Comment by GiridharaSPK** [comment]
DBSP is also not running in my system - raised an issue  (#[227](https://github.com/vmware/database-stream-processor/issues/227) ) in that project. 

The changes in the PR [#235](https://github.com/vmware/database-stream-processor/pull/235) of that project
when changed and tested is not creating any build-time error, but cannot run the project because there are no binary files generated.

**Comment by GiridharaSPK** [comment]
Tried running the latest commit - the build is successful, but IllegalThreadStateException is thrown followed by PSQLException relating to the authentication) due to which build failure is happening

<img width="1440" alt="Screen Shot 2022-11-17 at 4 40 18 PM" src="https://user-images.githubusercontent.com/27071146/202565474-9982da1f-aa3a-45c0-b36a-8a38d001b2af.png">


<img width="1440" alt="Screen Shot 2022-11-17 at 4 39 09 PM" src="https://user-images.githubusercontent.com/27071146/202565298-996437df-aeb8-4d8f-8e26-b50b47246e40.png">

**Comment by mbudiu-vmw** [comment]
You have to create a user account on postgres and supply to the script the account and password. They are the -u and -p flags in the script. The script is very short, take a look

**Comment by mbudiu-vmw** [comment]
Is this issue resolved?

**Comment by GiridharaSPK** [comment]
Yes
