### ISSUE TITLE
Compilation failure error 

### ISSUE THREAD

**Issue by GiridharaSPK** [vmware/sql-to-dbsp-compiler#62]
![sql-to-dbsp-java-error](https://user-images.githubusercontent.com/27071146/202528149-acb83aae-e7c8-462b-b68d-d1ff1971cbd6.png)

**Comment by mbudiu-vmw** [comment]
If it says "cargo not found" it means you have not installed Rust properly.

**Comment by GiridharaSPK** [comment]
Thanks for pointing it out. I tried installing cargo too, but it is still throwing the same error.

![Screenshot-sql-to-dbsp-error](https://user-images.githubusercontent.com/27071146/202535979-8d35ee8a-8b03-4ed6-91db-fddaeb78368f.png)

![Screenshot-sql-dbsp-error-2](https://user-images.githubusercontent.com/27071146/202536546-eab1ef54-bf00-4839-93da-0e28fb672caf.png)

**Comment by mbudiu-vmw** [comment]
I have pushed a change to main that is intended to fix the cargo error, but I don't know what to do about the Java error if you already have a new version of Java.

**Comment by mbudiu-vmw** [comment]
I assume we can close this issue, please reopen if that's not true.
